---
all:
  children:
    server:
      hosts:
        # due to port checks and manual inspection leaving single server
        #        nagios-ubuntu-2604:
        #  container_image: docker.io/geerlingguy/docker-ubuntu2604-ansible:latest
        #  container_command: /lib/systemd/systemd
        #  container_privileged: true
        #  container_volumes:
        #    - /sys/fs/cgroup:/sys/fs/cgroup:rw
        ktranslate-ubuntu-2404:
          container_image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
          container_command: /lib/systemd/systemd
          container_privileged: true
          container_volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
