.PHONY: test converge verify login destroy lint idempotence

test:
	molecule test

converge:
	molecule converge

verify:
	molecule verify

login:
	molecule login

destroy:
	molecule destroy

lint:
	ansible-lint
	yamllint .
	molecule lint

idempotence:
	molecule idempotence
