anro_ktranslate_molecule_snmp_url: http://172.29.0.20:8080/snmp.yaml
anro_ktranslate_molecule_device_url: http://172.29.0.20:8080/devices.json


molecule_anro_ktranslate_devices:
  devices:
    router01:
      device_name: router01
      device_ip: 172.29.0.21
    router02:
      device_name: router02
      device_ip: 172.29.0.22

molecule_anro_devices_snmp_config:
  100:
    id: "100"
    device_name: router01
    device_type: "snmpsim"
    ip: 172.29.0.21
    device_status: "V"
    device_description: "Molecule snmpsim device"
    sending_ips:
      - 172.29.0.21
    device_snmp_community: public
  101:
    id: "101"
    device_name: router02
    device_type: "snmpsim"
    ip: 172.29.0.22
    device_status: "V"
    device_description: "Molecule snmpsim device"
    sending_ips:
      - 172.29.0.22
    device_snmp_community: public

# full anro_ktranslate_snmp_config with no combining so that the verify validates properly and can load the configs.
anro_ktranslate_snmp_config:
  global:
    poll_time_sec: 60
    timeout_ms: 3000
    retries: 1
    drop_if_outside_poll: false
    mib_profile_dir: /etc/ktranslate/profiles
    mibs_db: /etc/ktranslate/mibs.db
    mibs_enabled:
      - HOST-RESOURCES-MIB
  trap:
    listen: "0.0.0.0:1620"
  discovery:
    cidrs: []
    ports:
      - 161
    default_communities:
      - public
    add_devices: false
    add_mibs: true
    threads: 4

anro_ktranslate_instances:
  - name: ktranslate-polling-molecule
    type: polling
    profile: polling
    enabled: true
    network: ktranslate-molecule
    ktranslate_args:
      api_device_file: /etc/ktranslate/devices.json
    ports:
      - "0.0.0.0:18082:8082/tcp"
    files:
      - name: snmp.yaml
        source: url
        url: "{{ anro_ktranslate_molecule_snmp_url }}"
        destination: /etc/ktranslate/snmp.yaml
        mode: "0644"
        read_only: true
        reload: signal
        reload_signal: USR2

      - name: devices.json
        source: url
        url: "{{ anro_ktranslate_molecule_device_url }}"
        destination: /etc/ktranslate/devices.json
        mode: "0644"
        read_only: true
        reload: signal
        reload_signal: USR2